<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="SixLabors.ImageSharp" />

    <ProjectReference Include="..\BookMyHall.Application\BookMyHall.Application.csproj" />
    <ProjectReference Include="..\BookMyHall.Application.Abstractions\BookMyHall.Application.Abstractions.csproj" />
    <ProjectReference Include="..\BookMyHall.Persistence\BookMyHall.Persistence.csproj" />
    <ProjectReference Include="..\BookMyHall.Domain\BookMyHall.Domain.csproj" />
    <ProjectReference Include="..\BookMyHall.Shared\BookMyHall.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" />
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />

    <Content Include="Email\Templates\**\*.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>