<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookMyHall.Domain\BookMyHall.Domain.csproj" />
    <ProjectReference Include="..\BookMyHall.Shared\BookMyHall.Shared.csproj" />
    <ProjectReference Include="..\BookMyHall.Contracts\BookMyHall.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
