name: BookMyHall CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration:
          - Release

    env:
      Solution_Name: BookMyHall.sln

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Display .NET Information
        run: dotnet --info

      - name: Restore NuGet Packages
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build Solution
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

      - name: Execute Unit Tests
        run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal